# Site settings
title: Pulperia
header-img: img/home-bg.jpg
email: leo@yanes.nyc
description: "Thoughts about everything"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: liopord
github_username:  leoyanes
facebook_username:  leo.yanesb

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
